# Generated by Django 5.1.1 on 2024-10-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_moviedata_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='images/None/Noimg.png', upload_to='images/'),
        ),
    ]
